---
- name: Deploy Calculator App Container
  hosts: localhost
  become: false

  tasks:
    - name: Pull the latest Docker image from Docker Hub
      community.docker.docker_image:
        name: dikshant0012/calculator-app
        source: pull

    - name: Run the Calculator App container
      community.docker.docker_container:
        name: calculator
        image: dikshant0012/calculator-app:latest
        state: started
        tty: true
        interactive: true
