input{
    file{
        path => "/usr/share/logstash/logs/calculator.log"
        start_position => "beginning"
        sincedb_path => "/dev/null"
    }
}

filter{
    grok{
        match => {"message"=>"%{TIMESTAMP_ISO8601:timestamp} \[%{DATA:thread}\] %{LOGLEVEL:level} %{JAVACLASS:logger} - %{GREEDYDATA:message_content}" }
    }

    date{
        match => ["timestamp", "ISO8601"]
        timezone => "UTC"
    }
}

output{
    elasticsearch{
        hosts => ["http://elasticsearch:9200"]
        index => "calculator-java-logs"
    }

    stdout { codec => rubydebug}
}